# apache
- name: install apache
  yum: name=httpd state=present
- name: start httpd
  service: name=httpd state=started enabled=yes
- name: add iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables regexp="{{ httpd_port }}" line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport {{ httpd_port }} -j ACCEPT" insertbefore="^# add end" state=present
