---
- hosts: 127.0.0.1
  sudo: true
  user: user
  vars:
    httpd_port: 80
    mysql_port: 3306
  tasks:
    - include: tasks/apache.yml
    - include: tasks/php.yml
    - include: tasks/mysql.yml
    - include: tasks/redis.yml
    - include: tasks/memcached.yml
    - include: tasks/mongodb.yml
