---
- hosts: 127.0.0.1
  sudo: true
  user: user
  vars:
    httpd_port: 80
    mysql_port: 3306
  tasks:
    # apache
    - name: install apache
      yum: name=httpd enablerepo=remi,epel state=present
    - name: start httpd
      service: name=httpd state=started enabled=yes
    - name: add iptables rule for httpd
      lineinfile: dest=/etc/sysconfig/iptables regexp="{{ httpd_port }}" line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport {{ httpd_port }} -j ACCEPT" insertbefore="^# add end" state=present
      notify: restart iptables
    # PHP
    - name: install php
      yum: name={{ item }} enablerepo=remi,epel state=present
      with_items:
        - php
    # MySQL
    - name: install mysql
      yum: name=mysql-server enablerepo=remi,epel state=present
    - name: add iptables rule for mysql
      lineinfile: dest=/etc/sysconfig/iptables regexp="{{ mysql_port }}" line="-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport {{ mysql_port }} -j ACCEPT" insertbefore="^# add end" state=present
      notify: restart iptables
    # memcach
    - name: install memcached
      yum: name=memcached enablerepo=remi,epel state=present
    # redis
    - name: install memcached
      yum: name=memcached enablerepo=remi,epel state=present
    #mongodb
    - name: install mongodb
      yum: name=mongodb enablerepo=remi,epel state=present
    # redis
    - name: install redis
      yum: name=redis enablerepo=10gen state=present
